version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    env_file:
      - ./.env
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER= "${DB_USER}"
      - MYSQL_PASSWORD= "${DB_PASSWORD}"
      - MYSQL_DATABASE= "${DB}"
      - MYSQL_ROOT_PASSWORD= "${DB_ROOT_PASSWORD}"
